### ISSUE TITLE
Parse error when trying to create_item

### ISSUE THREAD

**Issue by chxw** [ProdPerfect/monday#17]
**Error message**
`{'errors': [{'message': 'Parse error on ":" (COLON) at [6, 22]', 'locations': [{'line': 6, 'column': 22}]}], 'account_id': XXXXXXX}`
**Code**
```
from monday import MondayClient

board_id = '1223372619'
group_id = '#dev_frontend'
# create items for each component
for comp in components:
    r = monday.items.create_item(board_id, group_id, item_name=comp.name)
```
comp.name is a string.

**Comment by chdastolfo** [comment]
If you're still having this issue, please re-open it with more details and steps to reproduce, including the actual value of comp.name when you're receiving this error.
