### ISSUE TITLE
No means to query for complexity reset_in_x_seconds

### ISSUE THREAD

**Issue by lucioseki** [ProdPerfect/monday#27]
Monday.com API has a rate limit that resets every minute [0].
If I want to perform an expensive operation, but already spent too many "complexity points", I need to wait for x seconds before retrying.
Currently, this library has no way to query how many seconds I need to wait, so the safest approach is to wait for 60 seconds before retrying.

We can reduce this time by querying the actual time in seconds that we need to wait:
```
In [12]: monday.boards.client._send('query { complexity { reset_in_x_seconds } }', None)
Out[12]: '{"data":{"complexity":{"reset_in_x_seconds":44}},"account_id":8442039}'
```

This saves many hours of waiting time when handling several thousands of resources.

In the example above, I called `boards.client._send` in order to send this request.
Calling an internal method is not so neat. Also, `boards` has nothing to do with complexity points.

So what I suggest is:

a) Add a new resource `complexity`, so we can get the value by calling `monday.complexity.get_rate_limit_reset_time()`

and/or

b) Add a way to send arbitrary queries. This is already possible by calling `monday.<resource>.client._send(query)` with whatever resource, but it would be nice to have an official way to do this, like `monday.arbitrary_query(query)`.

[0] https://monday.com/developers/v2#queries-section-complexity

**Comment by rhymiz** [comment]
Hey @lucioseki , if you'd like to contribute by making this change, I'm happy to review! 
If not, we'll put it on our todo list and pick it up once we have more availability to work on it.

**Comment by lucioseki** [comment]
> Hey @lucioseki , if you'd like to contribute by making this change, I'm happy to review!

Great, thanks! I'll implement it.

**Comment by lucioseki** [comment]
The PR #29 allows me to retrieve current complexity budget and the time in seconds before the budget is reset:

```python3
In [2]: monday.complexity.get_complexity()
Out[2]: 
{'data': {'complexity': {'after': 1000000, 'reset_in_x_seconds': 60}},
 'account_id': 8442039}

In [3]: type(monday.users.fetch_users(limit=10))
Out[3]: dict

In [4]: monday.complexity.get_complexity()
Out[4]: 
{'data': {'complexity': {'after': 979850, 'reset_in_x_seconds': 41}},
 'account_id': 8442039}
```

This way, if I spend all my budget, I can retry after waiting for the retrieved `reset_in_x_seconds`:
```python3
def wait_and_retry(method, *args, **kwargs):
    response = method(*args, **kwargs)
    while response.get('errors'):
        print(response.get('errors'))
        response = monday.complexity.get_complexity()
        wait_interval = response['data']['complexity']['reset_in_x_seconds']
        print('gonna wait for', wait_interval, 'seconds')
        time.sleep(wait_interval)
        response = method(*args, **kwargs)

wait_and_retry(monday.users.fetch_users, limit=1000)
```

**Comment by chdastolfo** [comment]
Closing based on merge and release of PR 29
