### ISSUE TITLE
Is this project maintained?

### ISSUE THREAD

**Issue by jacopoch** [ProdPerfect/monday#37]
Hi,
is this project maintained anymore?

**Comment by Ashatz** [comment]
I am curious to know this as well.  To whomever is in charge of maintaining this project, please reach out to me at andrew.shatz@trix.solutions so that we may possibly work out a collaboration.  

Thank you!

**Comment by chdastolfo** [comment]
It is, yes ... sort of... or I try to maintain it as much as I can as just one person. Andrew, I'll reach out.
