### ISSUE TITLE
create_subitem not implemented

### ISSUE THREAD

**Issue by AtanasAtanasovIpsos** [ProdPerfect/monday#7]
There should be a method create_subitem. But I do not see it implemented.

**Comment by chdastolfo** [comment]
I've been meaning to do this - I can add this in next week.

**Comment by AtanasAtanasovIpsos** [comment]
nice! Thanks for the response.

**Comment by chdastolfo** [comment]
All right - `create_subitem` has been added in version 1.1.41 - this also resolves the mismatch between the README and some of the function signatures, so I'm going to close that issue as well. Thanks again!

**Comment by AtanasAtanasovIpsos** [comment]
Thanks for implementing this!
