### ISSUE TITLE
Fetch items with page limit

### ISSUE THREAD

**Issue by fcatullo** [ProdPerfect/monday#72]
From the Monday Web Site: "Querying items directly returns all items across the account. **Starting October 3rd, 2022**, you will not be able to return more than 100 items per query."
There is a way to page the fetch_items_by_board_id function?
Do you plan to update the package
Thanks
Fernando

**Comment by wbazant** [comment]
@fcatullo I have a workaround: https://github.com/ProdPerfect/monday/issues/68 would be really good if there was a package support for it!

**Comment by t-a-y-l-o-r** [comment]
@fcatullo I wrote an extension to the existing query to allow for pagination that just got approved: https://github.com/ProdPerfect/monday/pull/96

It won't pull everything, but you can wrap the call in a while loop like @wbazant above (maybe it's worth exposing a `fetch_all` kwarg? or a new func?)

We're just waiting on it to be released w/ 1.3.3

**Comment by chdastolfo** [comment]
Hi everyone - this has been released. Thanks for your input and patience!
