### ISSUE TITLE
Proxy handling

### ISSUE THREAD

**Issue by ravid1323** [ProdPerfect/monday#75]
Hi,

I can't use the class from my workplace lab which requires proxy
is there a way to add it?

**Comment by rhymiz** [comment]
Hi @ravid1323 ,

We don't currently have support for passing proxy configs to `requests` in the http client. 

You _could_ try setting the following environment variables and seeing if that works for you.
```bash
export HTTP_PROXY=1.2.3.4:123
export HTTPS_PROXY=1.2.3.4:123
```

More information on this in the [Requests docs](https://requests.readthedocs.io/en/latest/user/advanced/#proxies)

**Comment by chdastolfo** [comment]
Categorizing this as "won't do," as per the thread on [this](https://github.com/ProdPerfect/monday/pull/101) PR.
