### ISSUE TITLE
create_item needs an argument named item

### ISSUE THREAD

**Issue by AtanasAtanasovIpsos** [ProdPerfect/monday#8]
The official documentation for mutation create_item says the parameter should be named "item_name" however in this implementation it is called "item". This creates confusion.

**Comment by chdastolfo** [comment]
Too true, I'll fix this up. Thanks for pointing out!

**Comment by AtanasAtanasovIpsos** [comment]
No probs. Thanks for creating this package!

**Comment by chdastolfo** [comment]
Resolved in version `1.1.41`

**Comment by AtanasAtanasovIpsos** [comment]
Thanks!
