### ISSUE TITLE
Creating a Group

### ISSUE THREAD

**Issue by DolevAlgam** [ProdPerfect/monday#9]
Hey :)
Is there a way to create a group with this module?
I couldn't find a way to do so.

**Comment by chdastolfo** [comment]
Hi!
Sorry for the delayed response. There isn't currently a group resource on here (which seems weird...I guess I didn't need it at the time?), but I can work on adding that in the next week or so.

**Comment by DolevAlgam** [comment]
Hey :) I actually cloned and added it myself to the module, it dragged some new errors that the module didn't handle but I implemented a workaround for that.
The addition was pretty simple but if you want I can create a branch of the changes here.

**Comment by chdastolfo** [comment]
Ah sorry, I was too late. I've added them myself to the upcoming version. That said, I'm always curious to see what I can learn from other people's code, so if you're up for it feel free to create a branch! Thanks again.
